CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    readonly BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    author_name TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    CONSTRAINT posts_category_id_fkey 
    FOREIGN KEY (category_id) 
    REFERENCES categories(id)
    ON DELETE RESTRICT
);

CREATE INDEX posts_category_id_created_at_idx
ON posts (
    category_id,
    created_at DESC
)
WHERE deleted_at IS NULL;

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    author_name TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,

    CONSTRAINT comments_post_id_fkey
    FOREIGN KEY (post_id) 
    REFERENCES posts(id)
    ON DELETE CASCADE
);

CREATE INDEX comments_post_id_created_at_idx
ON comments (
    post_id,
    created_at ASC
)
WHERE deleted_at IS NULL;
