CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE posts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    author_name TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT posts_category_id_fkey 
    FOREIGN KEY (category_id) 
    REFERENCES categories(id)
    ON DELETE RESTRICT
);

CREATE INDEX idx_posts ON posts (category_id, created_at DESC);

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL,
    author_name TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

    CONSTRAINT comments_post_id_fkey
    FOREIGN KEY (post_id) 
    REFERENCES posts(id)
    ON DELETE CASCADE
);

CREATE INDEX idx_comments ON comments (post_id, created_at ASC);
