services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/agforest:cached
    command: sleep infinity
    environment:
      AGFOREST_SERVER_HOST: 0.0.0.0
      AGFOREST_SERVER_PORT: 3000
      AGFOREST_WORKER_THREADS: 8
      AGFOREST_MAX_BLOCKING_THREADS: 16
      AGFOREST_DATABASE_URL: postgres://vscode:root@database:5432/agforest
      AGFOREST_DATABASE_CONNECTION_LIMIT: 10

      DATABASE_URL: postgres://vscode:root@database:5432/agforest

  database:
    image: postgres:17-trixie
    environment:
      POSTGRES_USER: vscode
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agforest
